# Generated by Django 5.0.3 on 2024-04-03 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(verbose_name='add date')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('drink_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.drinktype')),
            ],
        ),
    ]
